### ISSUE TITLE
Please Update ReadME with new functions

### ISSUE THREAD

**Issue by swburchill** [jacwah/cutest#1]
I found your fix very helpful! Thanks for the question and link on stackoverflow. 

I would suggest to update the ReadME example usage to include the usage of your CuSuiteConsume() as well as addition of CuSuiteDelete() and CuStringDelete() and then update the AllTests.c accordingly. This would help others see how to achieve 0 leaks in valgrind with the cutest framework.

You should also add your name to the ReadMe for contributions as I think your fix is excellent and greatly needed. You should contact the original author to see about getting your fix merged in.

**Comment by jacwah** [comment]
Thanks for the feedback, I appreciate it!

I've tried to contact the author without success when I originally made the patch, but I might try again if I write the documentation you suggested.

**Comment by jacwah** [comment]
Fixed as of 14aabf185d063c758284b985bf495028779d4ced.
